version: '3.7'

services:
  odoo-app:
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: odoo-server
    restart: unless-stopped
    depends_on:
      - odoo-db
    ports:
      - "8069:8069"
    volumes:
      - odoo-web-data:/var/lib/odoo
      - ./config:/etc/odoo
      - ./addons:/mnt/extra-addons
    environment:
      - HOST=odoo-db
      - USER=odoo
      - PASSWORD=odoo
    command: >
      bash -c "
      if [ ! -f /var/lib/odoo/.initialized ]; then
        echo 'Database not found, running migrations...';
        odoo -i base --stop-after-init && touch /var/lib/odoo/.initialized;
      else
        echo 'Database already initialized.';
      fi;
      exec odoo"

  odoo-db:
    image: postgres:15
    container_name: odoo-server-db
    restart: unless-stopped
    environment:
      POSTGRES_DB: odoo
      POSTGRES_USER: odoo
      POSTGRES_PASSWORD: odoo
    volumes:
      - odoo-db-data:/var/lib/postgresql/data

  odoo-pgadmin:
    image: dpage/pgadmin4:latest
    container_name: odoo-server-pgadmin
    restart: unless-stopped
    depends_on:
      - odoo-db
    ports:
      - "5050:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@gmail.com
      PGADMIN_DEFAULT_PASSWORD: admin
    volumes:
      - pgadmin-data:/var/lib/pgadmin

volumes:
  odoo-web-data:
  odoo-db-data:
  pgadmin-data:
